### ISSUE TITLE
Error: @bigcommerce/checkout@1.293.0 dev: `nx run core:dev`

### ISSUE THREAD

**Issue by iovoz** [bigcommerce/checkout-js#1213]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/18189938/220933090-5354a0ba-ad96-44da-9eb5-ec84c738fcdd.png">

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/riovo/.nvm/versions/node/v14.21.2/bin/node',
1 verbose cli   '/Users/riovo/.nvm/versions/node/v14.21.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.17
3 info using node@v14.21.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @bigcommerce/checkout@1.293.0~predev: @bigcommerce/checkout@1.293.0
6 info lifecycle @bigcommerce/checkout@1.293.0~dev: @bigcommerce/checkout@1.293.0
7 verbose lifecycle @bigcommerce/checkout@1.293.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @bigcommerce/checkout@1.293.0~dev: PATH: /Users/riovo/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/riovo/Public/polygroup/checkout-js/node_modules/.bin:/Users/riovo/.nvm/versions/node/v14.21.2/bin:/Users/riovo/Public/google-cloud-sdk/bin:/Users/riovo/.yarn/bin:/Users/riovo/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/riovo/Public/google-cloud-sdk/bin:/Users/riovo/miniconda3/bin:/Users/riovo/miniconda3/condabin:/Users/riovo/.yarn/bin:/Users/riovo/.config/yarn/global/node_modules/.bin:/Users/riovo/.cargo/bin:/Users/riovo/Public/flutter/bin:/Users/riovo/Library/Android/sdk/emulator:/Users/riovo/Library/Android/sdk/tools:/Users/riovo/Library/Android/sdk/tools/bin:/Users/riovo/Library/Android/sdk/platform-tools:/Users/riovo/Public/flutter/bin:/Users/riovo/Library/Android/sdk/emulator:/Users/riovo/Library/Android/sdk/tools:/Users/riovo/Library/Android/sdk/tools/bin:/Users/riovo/Library/Android/sdk/platform-tools:/Users/riovo/.nvm/versions/node/v14.21.2:/Users/riovo/Library/Android/sdk/emulator:/Users/riovo/Library/Android/sdk/tools:/Users/riovo/Library/Android/sdk/tools/bin:/Users/riovo/Library/Android/sdk/platform-tools
9 verbose lifecycle @bigcommerce/checkout@1.293.0~dev: CWD: /Users/riovo/Public/polygroup/checkout-js
10 silly lifecycle @bigcommerce/checkout@1.293.0~dev: Args: [ '-c', 'nx run core:dev' ]
11 silly lifecycle @bigcommerce/checkout@1.293.0~dev: Returned: code: 1  signal: null
12 info lifecycle @bigcommerce/checkout@1.293.0~dev: Failed to exec dev script
13 verbose stack Error: @bigcommerce/checkout@1.293.0 dev: `nx run core:dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/riovo/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/Users/riovo/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid @bigcommerce/checkout@1.293.0
15 verbose cwd /Users/riovo/Public/polygroup/checkout-js
16 verbose Darwin 21.6.0
17 verbose argv "/Users/riovo/.nvm/versions/node/v14.21.2/bin/node" "/Users/riovo/.nvm/versions/node/v14.21.2/bin/npm" "run" "dev"
18 verbose node v14.21.2
19 verbose npm  v6.14.17
20 error code ELIFECYCLE
21 error errno 1
22 error @bigcommerce/checkout@1.293.0 dev: `nx run core:dev`
22 error Exit status 1
23 error Failed at the @bigcommerce/checkout@1.293.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by bc-peng** [comment]
Before getting to `nx run core:dev`, the process already failed at `nx run core:generate`.
Could you please run and find out what happened with `nx run core:generate`?

**Comment by iovoz** [comment]
It happend on M1 apple, fixed it by `npm install @swc/core`.
