### ISSUE TITLE
 random checkout error preventing checkout

### ISSUE THREAD

**Issue by mhittle** [bigcommerce/checkout-js#1309]
We get this error on ~30% of checkout and order confirmation page loads, starting the first week of May

Uncaught (in promise) Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. at t.render (react-dom.production.min.js:296:48) at l (renderOrderConfirmation.tsx:32:5) at Object.renderOrderConfirmation (loader.ts:87:21) at order-confirmation:154:41

**Comment by bc-peng** [comment]
Thank you for reaching out to us.

After reviewing the release history, we noticed that we introduced the React 17 upgrade during that period. Based on our observations, we have not observed any significant increase in the error rate since then.

We kindly request you to confirm whether you are using the native checkout or provide us with the URL of your store.

**Comment by gamlungJoeng** [comment]
It still appears, does bc's checkout.php detect that checkoutConfig and dom are generated before react render

**Comment by gamlungJoeng** [comment]
@bc-peng It still appears, does bc's checkout.php detect that checkoutConfig and dom are generated before react render

**Comment by mhittle** [comment]
> Thank you for reaching out to us.
> 
> After reviewing the release history, we noticed that we introduced the React 17 upgrade during that period. Based on our observations, we have not observed any significant increase in the error rate since then.
> 
> We kindly request you to confirm whether you are using the native checkout or provide us with the URL of your store.

We've made some modifications, which have worked fine until now. https://www.cabinetnow.com

**Comment by bc-peng** [comment]
Hi @mhittle, I can see this store is on the native/reference checkout `v1.347.1`.
Would you mind sharing with other developers what you changed to improve it?

**Comment by mhittle** [comment]
We haven't improved it. The issue persists. It's intermittent and stochastic.

**Comment by bc-0dp** [comment]
Hi @mhittle 
Just following up here, any improvements on the issue?

**Comment by animesh1987** [comment]
We added some fix on the backend for this, and have changed the loading order of scripts which seem to have resolved the issue. Seems to be no activity hence closing this.
