### ISSUE TITLE
Issue With Error Tracing When Building

### ISSUE THREAD

**Issue by Volence** [bigcommerce/checkout-js#215]
Occasionally after making some edits to the checkout, when I try to build I'll get the error message `Error: Cannot find module '.../checkout/dist/manifest.json' `. I know the dist folder gets removed immediately, so a new manifest must be created and it's not being created, but there's no logging as to what's causing it not be created. I fixed this once by removing some custom SCSS on RockBottomGolf's checkout (again, not sure what the problem was, just commented out my changes till I narrowed it down), and it removed the vague error. It does compile in /build while in dev mode though.

Here's what I get in my terminal when running `npm run build`

`Using 1 worker with 2048MB memory limit                                                                                 
Error: Cannot find module '/mnt/c/Users/18-5/stencil/checkout/dist/manifest.json'                                       Require stack:                                                                                                         
- /mnt/c/Users/18-5/stencil/checkout/webpack.config.js                                                                  
- /mnt/c/Users/18-5/stencil/checkout/node_modules/webpack-cli/bin/utils/convert-argv.js                                 - /mnt/c/Users/18-5/stencil/checkout/node_modules/webpack-cli/bin/cli.js                                                - /mnt/c/Users/18-5/stencil/checkout/node_modules/webpack/bin/webpack.js                                                    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)                                             at Function.Module._load (internal/modules/cjs/loader.js:690:27)                                                        at Module.require (internal/modules/cjs/loader.js:852:19)                                                               
at require (/mnt/c/Users/18-5/stencil/checkout/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)                
at EventEmitter.<anonymous> (/mnt/c/Users/18-5/stencil/checkout/webpack.config.js:231:67)                               at EventEmitter.emit (events.js:210:5)                                                                                  
at onDone (/mnt/c/Users/18-5/stencil/checkout/webpack.config.js:124:42)                                                 at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/c/Users/18-5/stencil/checkout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:36:1)                                                                                at AsyncSeriesHook.lazyCompileHook (/mnt/c/Users/18-5/stencil/checkout/node_modules/tapable/lib/Hook.js:154:20)         
at onCompiled (/mnt/c/Users/18-5/stencil/checkout/node_modules/webpack/lib/Compiler.js:271:21)                          at /mnt/c/Users/18-5/stencil/checkout/node_modules/webpack/lib/Compiler.js:671:15                                       at eval (eval at create (/mnt/c/Users/18-5/stencil/checkout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)                                                                                                               at callback (/mnt/c/Users/18-5/stencil/checkout/node_modules/stylelint-webpack-plugin/lib/run-compilation.js:57:5)      
at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/c/Users/18-5/stencil/checkout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)                                                                                 at AsyncSeriesHook.lazyCompileHook (/mnt/c/Users/18-5/stencil/checkout/node_modules/tapable/lib/Hook.js:154:20)         
at /mnt/c/Users/18-5/stencil/checkout/node_modules/webpack/lib/Compiler.js:668:31                                       at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/c/Users/18-5/stencil/checkout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)                                                                                 at AsyncSeriesHook.lazyCompileHook (/mnt/c/Users/18-5/stencil/checkout/node_modules/tapable/lib/Hook.js:154:20)        
at /mnt/c/Users/18-5/stencil/checkout/node_modules/webpack/lib/Compilation.js:1385:35                                   at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/c/Users/18-5/stencil/checkout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)                                                                                 at AsyncSeriesHook.lazyCompileHook (/mnt/c/Users/18-5/stencil/checkout/node_modules/tapable/lib/Hook.js:154:20)         
at /mnt/c/Users/18-5/stencil/checkout/node_modules/webpack/lib/Compilation.js:1376:32                                   at eval (eval at create (/mnt/c/Users/18-5/stencil/checkout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)                                                                                                           npm ERR! code ELIFECYCLE                                                                                                
npm ERR! errno 1                                                                                                        
npm ERR! @bigcommerce/checkout@1.17.1 build: `rm -rf dist && webpack --mode production`                                 npm ERR! Exit status 1                                                                                                  
npm ERR!                                                                                                                
npm ERR! Failed at the @bigcommerce/checkout@1.17.1 build script.                                                       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                              npm ERR! A complete log of this run can be found in:                                                                    
npm ERR!     /home/stevenrng/.npm/_logs/2020-01-23T15_55_15_489Z-debug.log                                              `

**Comment by davidchin** [comment]
We now have a guide on how to install a custom checkout. Please refer to this [link](https://developer.bigcommerce.com/stencil-docs/customizing-checkout/installing-custom-checkouts) for more information. Thank you!
